Fix Unsafe Browser starting if chroot setup fails
Closes #20431

diff --git a/config/chroot_local-includes/usr/local/sbin/unsafe-browser b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
--- a/config/chroot_local-includes/usr/local/sbin/unsafe-browser
+++ b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
@@ -112,15 +112,27 @@ fi
 
 show_start_notification
 
+# Clean up the chroot on exit
+# shellcheck disable=SC2064
+trap "try_cleanup_browser_chroot \"${CHROOT}\" \"${COW}\"" INT EXIT
+
 echo "* Setting up chroot"
-setup_chroot_for_browser "${CHROOT}" "${COW}" "${BROWSER_USER}" || \
-    error "$(gettext "Failed to setup chroot.")"
+# This `set +e` dance with a subshell is necessary to have `set -e` work
+# in the called function and be able to act on its return value. See:
+# https://stackoverflow.com/a/11092989
+set +e
+(set -e; setup_chroot_for_browser "${CHROOT}" "${COW}" "${BROWSER_USER}"); ret=$?
+set -e
+[ $ret -eq 0 ] || error "$(gettext "Failed to setup chroot.")"
 
 echo "* Configuring chroot"
-configure_chroot_browser "${CHROOT}" "${BROWSER_USER}" "${BROWSER_NAME}" \
-    "${HUMAN_READABLE_NAME}" "${HOME_PAGE}" \
-    /usr/share/tails/chroot-browsers/unsafe-browser/extensions/*.xpi || \
-        error "$(gettext "Failed to configure browser.")"
+set +e
+(set -e; configure_chroot_browser "${CHROOT}" "${BROWSER_USER}" \
+    "${BROWSER_NAME}" "${HUMAN_READABLE_NAME}" "${HOME_PAGE}" \
+    /usr/share/tails/chroot-browsers/unsafe-browser/extensions/*.xpi); ret=$?
+set -e
+[ $ret -eq 0 ] || error "$(gettext "Failed to configure browser.")"
+
 if ! nm_is_connected; then
     error "$(gettext "You are not connected to a local network yet.\n\nTo be able to start the Unsafe Browser, you first need to connect to a Wi-Fi, wired, or mobile network.")"
 fi
